services:
  payload:
    image: node:22-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: >
      sh -c "
      corepack enable &&
      corepack prepare pnpm@10.0.0 --activate &&
      pnpm install &&
      pnpm dev
      "
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: pagbutlakuser
      POSTGRES_PASSWORD: pagbutlakpass
      POSTGRES_DB: pagbutlakdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: none

volumes:
  pgdata:
  node_modules:
